# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: power_enum 2.7.1 ruby lib

Gem::Specification.new do |s|
  s.name = "power_enum"
  s.version = "2.8.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Trevor Squires", "Pivotal Labs", "Arthur Shagall", "Sergey Potapov"]
  s.cert_chain = ["gem-public_cert.pem"]
  s.date = "2014-12-20"
  s.description = "Power Enum allows you to treat instances of your ActiveRecord models as though they were an enumeration of values.\nIt allows you to cleanly solve many of the problems that the traditional Rails alternatives handle poorly if at all.\nIt is particularly suitable for scenarios where your Rails application is not the only user of the database, such as\nwhen it's used for analytics or reporting.\n"
  s.email = "arthur.shagall@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    "lib/active_record/virtual_enumerations.rb",
    "lib/generators/enum/USAGE",
    "lib/generators/enum/enum_generator.rb",
    "lib/generators/enum/enum_generator_helpers/migration_number.rb",
    "lib/generators/enum/templates/model.rb.erb",
    "lib/generators/enum/templates/rails31_migration.rb.erb",
    "lib/generators/virtual_enumerations_initializer/USAGE",
    "lib/generators/virtual_enumerations_initializer/templates/virtual_enumerations.rb.erb",
    "lib/generators/virtual_enumerations_initializer/virtual_enumerations_initializer_generator.rb",
    "lib/power_enum.rb",
    "lib/power_enum/enumerated.rb",
    "lib/power_enum/has_enumerated.rb",
    "lib/power_enum/migration/command_recorder.rb",
    "lib/power_enum/reflection.rb",
    "lib/power_enum/schema/schema_statements.rb",
    "lib/testing/rspec.rb"
  ]
  s.homepage = "http://github.com/albertosaurus/power_enum_2"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.2.2"
  s.signing_key = "gem-private_key.pem" if File.exists?('gem-private_key.pem')
  s.summary = "Allows you to treat instances of your ActiveRecord models as though they were an enumeration of values"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 4.0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 3.1"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["~> 4.0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 3.1"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 4.0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 3.1"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
  end
end

